---
title: "Limitations of the data"
date: "2022-11-29"
categories: [data]
---

A question I get often when I'm doing a talk is, "what are the limitations of the data that you're using?" And it's a great question. We should always think what our data can tell us and what it cannot.

One of my first data sources is a large children's cohort study. The strengths of this data is that it has rich, repeated measures about adherence to NPIs, about parent-reported infection, symptoms, sociodemographics, lifestyle, child health behaviours. It samples from primary care, which is great because we know that more than 95% of children access primary care in the first few years of life.

However, it also comes with another limitations. I will frame these limitations in terms of the three types of bias: selection bias, measurement error, and confounding.

**Selection bias:** Like many other cohorts, it suffers from selection processes that make it easier for richer, more educated, whiter participants to participate in the study. This may limit its external generalizability. Another limitation, in the some vein, is that richer, more educated families tend to remain in the study longer than those who are not. What does that mean? Well, if richer, whiter people are more likely to adhere to masks, and they are also less likely to get infected, and it would bias the resut away from the null.

**Measurement error:** Like other studies that use survey data, there is a certain amount of measurement error that comes along with questionnaires. For example, families might have trouble recalling how many days their child was adherent to masks. There may be some measurement error associated with self-report of rapid antigen tests, which in themselves have imperfect diagnostic accuracy, which then must get reported correctly by parents. Moreover, the tests must be administered properly, which may not occur.

**Confounding:** One of the strengths of cohort studies is that they can collect really rich confounder information. For example, TARGet Kids! has great information not only on child NPI adherence, but they also have information on parent NPI adherence, household income, maternal and paternal education. However, there are measures that we have not collected--for example, as much as we can try to control for 'health seeking behaviour' through other measures (visits to the doctor, flu shot in past few months, perception about health), there may still may be some residual confounding.

The next data source are population health administrative data. This is data that is usually collected for billing and administrative purposes. Strengths of administrative data include the fact that it is population-wide--in our data, we can capture every single community dwelling child that obtained a vaccine in the province. This means we have a lot of data--a lot more than if we were to look at, for example, cohort data--which enables us to get more precise estimates. Administrative is also fast and efficient- data is recorded in real time, enabling us to get answers quickly. And lastly, administrative data is extremely resource-efficient; we do not require RAs, infrastructure to collect this data, as it is already being collected for administrative and financial purposes.

Because this data is not being collected for research purposes, it also comes with a number of drawbacks:

**Selection biases**: Selection biases still exist will health administrative data (even though they do capture every encounter with the healthcare system), because they require participants to have access to the healthcare system. Unequal access is common, and in our case, it is exacerbated by government restriction on testing at the end of December 2021. In the third study, we are restricted to participants who were able to access testing for their child. For the most part, this included children of essential workers working (including physicians). However, although government restirictions were the same across Ontario, the manner in which they were implemented from hospital to hospital differed. This may mean that the external generalizability of our results to the general Ontario population may be limited.

**Measurement error**: Health administrative data can suffer from undercoding or miscoding of variables. It is unlikely for vaccinations to be miscoded, given the stringency of the vaccination protocol and the tracking of every single dose. PCR testing does not have perfect sensitivity and specificity, though it is considered the gold standard for testing for SARS-CoV-2.

**Confounding**: Because this data is not collected for research purposes, there are a number of variables that may be important confounders for which we lack information. For example, many individual-level sociodemographics are not available--income, ethnicity, education. For our VE study, we use area-level sociodemographics as a proxy. These include neighbourhood income quintile, essential worker status quintile, and large household size quintile. These may or may not serve as good proxies for individual-level characteristics.

These data sources come with their limitations. However, they also come with a number of complementary strengths- the cohort has information that ICES lacks, and ICES has information that the cohort lacks, and it also covers many many children. It is important to leverage these strengths to make the most out of available data to answer important questions about SARS-CoV-2 in children.
