---
title: "Decomposition and probabilities"
date: "2022-12-02"
categories: [mediation]
---

Now to move onto something a bit different. Decomposition! Decomposition is the process of separting effects into an indirect and direct effects for mediation analysis.

Long story short- but we want to obtain the 'nested counterfactuals'--ie. what the expected value would be if the mediator had acted in a way differnt than the actual treatment received.

Let's start with direct-indirect decomposition.

The formula for this is TE = NIE + TDE

Where $TE=E[Y^{(1,M^1)}]-E[Y^{(0,M^0)}]$ (both switches on minus both switches off)

which, if we add and subtract this term, called the nested counterfactual: $E[Y^{(1,M^0)}]$

turns into: $TE=E[Y^{(1,M^1)}]-E[Y^{(1,M^0)}] + E[Y^{(1,M^0)}]-E[Y^{(0,M^0)}]$

Great! Now how do you get each of these terms? Remember, each term is made up of an exposure set to a value, with a mediator taking on one of two values, 0 or 1 (because 'M under A=1' can be either 0 or 1). We need to take a weighted average of each of those scenarios.

The first and last terms are easy:

$E[Y^{(1,M^1)}]=E[Y|A=1,M=1]*Pr(M=1|A=1) + E[Y|A=1,M=0]*Pr(M=0|A=1)$

Basically, it's expected value of Y when A is set to 1 and M is also 1 weighted by the probability that M would take the value of 1 when A is set to 1 PLUS the expected value of Y when A is set to 1 and M is 0, weighted by the probability that M would take the value of 0 when A is set to 1.

The nested counterfactual is tricky:

$E[Y^{(1,M^0)}]=E[Y|A=1,M=1]*Pr(M=1|A=0)+E[Y|A=1,M=0]*Pr(M=0|A=0)$

Here, A remains fixed at 1, but M *acting as if A were 0* can take on two values, 0 or 1. The term $E[Y^{(1,M^0)}]$ means we need to add up the probabilities of those two scenarios. Before, it was easy- we basically took a weighted average of the two possible values of the mediator. The weights were easy because it was the observed probability-- the probability of M conditional on the exposure level we actually saw.

This time, which probability do we take? In the previous example, we were interested in M 'as if A were equal to 1'. Well guess what? A is equal to 1, so we simply weight by the probabilities that we see M=1 or M=0 in the category of the actual exposure value, A=1. This time, remember we are interested in M 'as if A were equal to 0'. Well, this time, our actual exposure value A is equal to 1, how can we see M 'as if A were equal to 0'? No such group really exists. This is why we need to look to the other group, A=0, and see the probability that M would take on 1 or 0 **in this group**. and multiply this by the expected value of the a scenario we *can* see.
