---
title: "Consequences of exclusion criteria in my cohort data"
date: "2022-12-09"
categories: [study design, bias]
---

People who are be excluded from the cohort I am analyzing are children who had chronic diseases at the time of enrolment into the study as well as families that do no speak English.  

These chronic conditions included failure to thrive (1-10% of children in high income countries), cerebral palsy (1 to 4 per 1000), cystic fibrosis (1 in 3500), and congenital anomalies (3.5 to 14 in 10,000).  Children with asthma and high-functioning autism were allowed to enrol in the study. One question that might be asked, is how will excluding children with chronic conditions impact your results?  We had excluded these children because the original aims of the study were about healthy growth.  If our target population does not include children with chronic conditions, and we don't want to make inferences to this population, then we can simply say that doing so is beyond the scope of this study.  And there are good reasons to limit it to children without chronic conditions--namely, that children with chronic conditions may have health behaviours and health outcomes (e.g. more severe infection) that are different than otherwise healthy children, and that these children represent a different population that probably deserves their own study. 

If you think of chronic conditions as a confounder, i.e. children with chronic conditions are more likely to adhere to NPIs, and they are more likely to have maybe more severe manifestations of Covid (i.e. less likely to be asymptomatic), then including children with chronic conditions and not adjusting for them will lead to bias.  What this will do is bias the estimate toward the null, because if you can imagine, we will have more exposed infecteds.

Another question I get often is how will the exclusion of non-English speaking families impact your results?  Cohorts often have this exclusion criterion for two reasons.  First, translation of questionnaires (unfortunately) is a very expensive endeavour.  Another thing about longitudinal cohort studies is that the long-term relationships that they build with research assistants often keeps families in the study and is key to repeated follow-up. Unfortunately, having research assistants who are able to speak the multitude of languages that are spoken especially in a diverse place such as Toronto is challenging.  

So by excluding non-English speaking families, we can't really generalize to this group.  We also can't make inferences to groups that don't attend primary care, as our cohort is a primary care network.  We know that more than 90% of children in Ontario attend primary care within the first few years of their life, which makes primary care an excellent source population for our study, but we still miss individuals.  Also, I'm not convinced right now that there is a link between sociodemographic indicators, including non-English speaking, and NPI adherence.  What we're seeing is that we're seeing highly affluent and educated individuals being non-adherent.  And when we don't have that link, confounding bias by non-English speaking may be negligible. 

However, another way to think of these exclusion criteria is through selection bias.  Sometimes what happens is that our exclusion criteria means we are conditioning on common effects, or on variables that are descendants of both the exposure and the outcome.  Fortunately, chronic illness and language speaking are likely common causes of both the exposure and the outcome (and unlikely to be caused by descendants of the exposure or outcome), and so selection bias is not an issue here. 
