---
title: "Test Negative Studies: Let's Talk About It"
date: "2022-11-28"
categories: [R, Covid-19, study design, test-negative]
---

If you've been keeping up with the Covid-19 vaccine literature, there may be a study design that sticks out to you: a test-negative study. Huh? What's that?

Before we get into what a test negative study is, let's think about what these vaccine effectiveness studies want to examine. The exposure in these studies is typically vaccination status (0,1,2 doses, typically with 0 as the referent category), and the outcome is SARS-CoV-2 infection. The question is, what is the real-world impact of vaccines on SARS-CoV-2 infection?

**But back up--why do we need to know real-world effectiveness of vaccines?** Don't we have RCT data on how well the vaccines work? Yes, we do- but these RCTs typically have very stringent inclusion criteria (children have to be very healthy, etc.), and the families that self-select into these studies tend to be very affluent, well-connected, educated. Moreover, RCTs tend to have very regimented follow-up and dosing---families are reminded that they need to come in for their second dose, an RCT coordinator makes sure they receive it, vaccine administration is highly protocol-ized (vaccine expiration and storage are well-monitored). In the real world, it doesn't always happen this way. You've got kids who are maybe not the healthiest--they might have chronic conditions like asthma. Families aren't always rich and educated. Families may not come for their second dose, or may not come on time. Vaccine distribution is challenging, with changes in expiry and variable storage abilities. If we want to make inference to a population that deals with these system-level challenges, that has some health conditions, that are not as rich/well connected, then we need to do real-world effectiveness studies.

**Ok, so how do we do this?** In an ideal world, we could conduct a prospective cohort study---recruit children, follow them up over time, surveil them daily to see who got infected with SARS-CoV-2 and when. Sounds simple right? The problem is that this is really, really resource intensive. You need to follow a lot of children to have precise estimates. You need to test these children every day, and even if you tested them weekly, this can mean thousands upon thousands of PCR tests. You might have hard time finding families/children who are willing to do this.

Ok. So cohort studies are too expensive. What the next best thing? The next best thing might be a population-based case control study. Here we would have complete case ascertainment, and we would select a random sample of population controls. This study, in essence, could be viewed as nested within the cohort, with missing data (i.e. controls we did not select) as missing at random. In other words, according to Sullivan, this would be a cohort study in which the statum of people who do not test are ignored.
This study would be much cheaper, as we wouldn't have to do hundreds of thousands of PCR tests. But population controls are challenging---the way that they are ascertained might be different from the way cases as ascertained. The population controls might be very different than the cases. In our scenario, cases are ascertained through testing centres or pharmacies or other places that do PCR tests. These people might have better access to healthcare than the general population. This means the cases and conrols will be non-exchangeable--there are confounding factors that will impact case ascertainment as well as vaccination status, meaning there will be bias.

OK. What about a case-control study with 'other' patient controls--i.e. people who can access the testing centres and pharmacies. Now we're onto something. These controls are more like our cases---there is some indirect matching going on here. This brings us to the test-negative study. **A test-negative study recruit participants who attend Covid assessment centres and test positive for Covid-19; controls are participants who undergo the same tests for the same reasons as the cases, but test negative.**

The advantage of test-negative studies is that they have similar participation rates between cases and controls, similar information quality and completeness, and similar access. A particular advantage of test-negative studies is that they compare individuals with similar health seeking-behaviour and access to testing. We might imagine that a person who is more likely to seek vaccines is probably also more likely to find a way to get a PCR test. This is especially important given testing restrictions, which excluded many individuals from obtaining a test after December 2021. Residual confounding might also be less of a concern in test negative studies because (see Shi et al) variables that impact vaccination status are similar for Covid-19 and non-Covid-19 respiratory infections (e.g. children with parents who are healthcare workers might be more likely to get the vaccine, but the proportion of children with healthcare workers who have Covid-19 versus some other respiratory infection is probably the same).

Some people have had been critical of test-negative designs. Westreich et al. state that test-negative designs are not really case-control studies as controls are not formally sampled from the source population. However, as Vandenbroucke and Pearce point out, there is a broad class of case control studies that use 'other' patient controls, which can sometimes help with exchangeability between the cases and controls. These designs using 'other' patient controls can provide valid estimates when (according to Jackson and Nelson) a) other respiratory viruses are not impacted by the vaccine and b) vaccine effectiveness does not vary by health-care seeking behaviour.

Others have asserted that a test-negative study is a cohort study with some incomplete follow-up. However, there is no follow-up happening in test negative designs because case and control status are ascertained at a single point in time: the time of the test (Vandenbrocke and Pearce).

However, under the assumption of no confounding, selection bias, misclassification and assuming parametric assumptions are met, the test-negative study can provide valid estimates of vaccine effectiveness.
